### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by JonZeolla** [set-element/auditd_policy#1]
Just to clarify, is the intent of this to use Bro as more of a correlation engine than a network analysis tool?  What is the benefit of doing this over using rules in a HIDS tool like OSSEC?  This seems to centralize the load instead of distributing the load - which could be helpful if there are other correlation opportunities.

**Comment by set-element** [comment]
Greetings,

The design for this is drawn to a large degree from the instrumented ssh
work that I have done in that there are a large number of agnostic event
generators (the python scripts running on the end hosts that are
normalizing the auditd data and stunneling it over to the worker host).
These events are logged to create a permanent record of actions safely away
from the host where the user is operating.  In parallel the event stream
has the local site security policy applied against it and more
stateful/heavy analysis as well (like tracking user behavior over time).

I am doing a dreadful job of describing how this works - some sort of
documentation is in order this week which will help a great deal.  I can
post it to github as well as send you a copy when I am done.

I did not use something like ossec because (1) I am not that familiar with
it and do not know if it can do the long term stateful analysis I need and
(2) I have built out a bunch of host side analysis using bro of which
auditd is just a part of the picture.  The implementation of this will be
at a supercomputing facility at LBNL called NERSC (www.nersc.gov) which is
similar in nature to PSC in Pittsburgh.  If you are going to the brocon at
MIT (https://www.bro.org/community/brocon2015.html) I am hoping to present
there and will be explaining this in more detial.

Hope this answers any questions, but by all means feel free to ask again if
this is making no sense.

cheers,
scott

**Comment by JonZeolla** [comment]
Thanks, Scott.  I will not be at brocon this year because it conflicts with black hat/defcon, although I did make it last year.  OSSEC does not do a great time at long term analysis, but it could create alerts after parsing auditd logs and feed them into something like an ELK stack for those longer term trends.  I'd love to talk more details about the work you're doing since I'm going to miss BroCon.  Feel free to reach out - contact info is just a quick google search away.  
- Jon
